apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: test-pipeline-remote-oci-ta
  namespace: brianwcook-tenant
spec:
  params:
  - name: git-url
    type: string
    default: ""
  - name: revision
    default: "main"
    type: string
  - name: platform
    type: string
    default: "linux/amd64"
    description: architecture to execute the test pipeline on
  - name: user-image
    type: string
    description: the image to use when executing the test sscript
  - name: user-exec
    type: string
    description: the command to run to execute the test

  results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.test-runner-remote-oci-ta.results.TEST_OUTPUT)
  tasks:
    - name: test-runner-remote-oci-ta
      params:
        - name: platform
          value: $(params.platform)
        - name: user-exec
          value: $(params.user-exec)
        - name: user-image
          value: $(params.user-image)
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/brianwcook/test-runner-remote-oci-ta
        - name: revision
          value: main
        - name: pathInRepo
          value: test-runner-remote-oci-ta.yaml
status: {}
