apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: test-pipeline-remote-oci-ta
  namespace: brianwcook-tenant
spec:
  params:
  - name: git-url
    type: string
    default: ""
  - name: revision
    default: "main"
    type: string
  - name: platform
    type: string
    default: "linux/amd64"
    description: architecture to execute the test pipeline on
  - name: user-image
    type: string
    description: the image to use when executing the test sscript
  - name: user-exec
    type: string
    description: the command to run to execute the test

  results:
    - description: ""
      name: TEST_OUTPUT
      value: $(tasks.test-runner-remote-oci-ta.results.TEST_OUTPUT)
      
  tasks:
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
        - name: name
          value: git-clone-oci-ta
        - name: bundle
          value: quay.io/redhat-appstudio-tekton-catalog/task-git-clone-oci-ta:0.1@sha256:e3490635200600da4a6b2997b0cf8e65e012155e7795824aa36d858a890ad31f
        - name: kind
          value: task
      params:
      - name: url
        value: "$(params.git-url)"
      - name: revision
        value: "$(params.revision)"
      - name: ociStorage
        value: "quay.io/redhat-user-workloads/brianwcook-tenant/konflux-builds/test-runner-remote-oci-ta:$(context.pipelineRun.name).git"
      - name: ociArtifactExpiresAfter
        value: 5d
      workspaces:
      - name: basic-auth
        workspace: git-auth
    - name: test-runner-remote-oci-ta
      runAfter:
      - clone-repository
      params:
        - name: PLATFORM
          value: $(params.platform)
        - name: user-exec
          value: $(params.user-exec)
        - name: user-image
          value: $(params.user-image)
        - name : SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      taskRef:
        resolver: git
        params:
        - name: url
          value: https://github.com/brianwcook/test-runner-remote-oci-ta
        - name: revision
          value: main
        - name: pathInRepo
          value: test-runner-remote-oci-ta.yaml
  workspaces:
  - name: git-auth
    optional: true
status: {}
